version: '2'

services:
    database:
        container_name: database.server.com
        image: cassandra
        volumes:
            - ./data:/var/lib/cassandra
        networks:
            - shortlink_network

    cache:
        container_name: cache.server.com
        image: redis
        networks:
            - shortlink_network

    link-server:
        container_name: link.server.com
        image: link.server.com
        build:
            context: ./link-server
        environment:
            - DATABASE_SERVER=database.server.com
            - DATABASE_KEYSPACE=shortlink_db
            - HOST=0.0.0.0
            - PORT=5300
        ports:
            - 5300:5300
        networks:
            - shortlink_network
        links:
            - database
            - cache
        depends_on:
            - database
            - cache

networks:
    shortlink_network:
        driver: bridge
